name: Deploy
on:
  push:
    branches:
      - 'master'
env:
  TF_IN_AUTOMATION: 1
  TF_INPUT: 0
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform CLI
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_ACCESS_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -diff -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan -lock-timeout=300s
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -lock-timeout=300s
